site_name: ZK Puzzle Writeups
site_author: Xor0v0
site_url: https://xor0v0.github.io/ZK-Puzzle-Writeups/
copyright: Copyright &copy; 2024 - 2030 Xor0v0
  
# Repository
repo_name: 'Xor0v0/ZK-Puzzle-Writeups'
repo_url: https://github.com/Xor0v0/ZK-Puzzle-Writeups

nav:
    - 简介:
        - 首页: index.md
    - Crypto:
        - Oven: crypto/oven.md
        - Let's hash it out: crypto/lets-hash-it-out/lets-hash-it-out.md
        - SafeEscrow: crypto/safeescrow.md

# Theme
theme:
    name: 'material'
    # custom_dir: docs/overrides
    language: 'zh'
    palette:
      primary: 'white'
      accent: 'teal'
    icon:
      logo: material/school
    features:
      - navigation.tabs
      - navigation.top
      - navigation.tracking
      - search.suggest
      - search.highlight
      - search.share
    font:
      text: 'Fira Sans'
      code: 'Fira Mono'


plugins:
    - search
    - git-revision-date-localized:
        type: datetime
        timezone: Asia/Shanghai
        locale: zh
    - git-authors
    - blogging:
        theme:
          name: card
        features:
          tags:
            insert: top
        size: 5
        paging: false
        show_total: false
        dirs:
          - blockchain
          - crypto
          # - misc
          # - pwn
          # - reverse
          # - web


extra_javascript:
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    - https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

# Extensions
markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
        linenums: true
    - def_list
    - footnotes
    - meta
    - toc:
        permalink: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.progressbar
    - pymdownx.smartsymbols
    - pymdownx.superfences:
        custom_fences:
          - name: math
            class: arithmatex
            format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
